version: '3'
services:
  mc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25565:25565"
    volumes:
      - /docker/mc/vanilla_1.19/server/:/server
    tty: true
